### ISSUE TITLE
RSS Feed with full content

### ISSUE THREAD

**Issue by RolandStuder** [marcojakob/lilo-blog#5]
Ich verstehe, dass ihr für eure Federation einen reduzierten Feed braucht, aber als Benutzer von RSS Feeds ignoriere ich eigentlich feeds die mich zum Lesen eines Artikels zwingen den Reader zu verlassen.

Deshalb braucht es in meinen Augen einen Feed der den gesamten Artikel Content enthält.

**Comment by marcojakob** [comment]
There are two feeds currently:

- Atom (RSS): `/index.xml`
- JSON: `/index.json`

For the aggregation platform we are using the JSON feed. It includes just the summaries. According to the [JSON Feed "standard"](https://jsonfeed.org/version/1) we should also include the content either as text or html. But I hesitated to do this because it will get very large if someone has a lot of posts.

We could do pagination - but this makes it much harder handle updates for the aggregation platform. 

Do you think that feed readers really need the full content inside the RSS feed? What are you using.

BTW: If you have a look at the default Hugo template for RSS it only includes summaries: https://gohugo.io/templates/rss/#the-embedded-rss-xml

**Comment by RolandStuder** [comment]
Feed reeders only ever present, what you send them in the feed file. For people using readers a full content feed is much more practical, and it is what I get with almost all the sites.

Many feeds only provide the last 10, 20 or 30 articles, the feed does not need to be a full map of all the articles, it's purpose is to serve inform you about new things. So size is not really an issue and even then, the feeds only serve html, no media, so filesize is not actually that big.

To only provide a summary is mainly interesting, if you want drive traffic to your site, for people using feedreaders it's not so nice. Personally I get annoyed with these feeds and rarely read their articles.

btw: I am using https://feedly.com

**Comment by marcojakob** [comment]
Lernblog [version 1.5.0](https://github.com/marcojakob/lernblog/releases/) and above include full RSS content and RSS pagination.

Note: We will probably remove the JSON-Feed as it does not seem to be more established than three years ago (https://www.jsonfeed.org/).
